import i18nConfig from '../../../i18nConfig'
import { dir } from 'i18next'
// import localFont from 'next/font/local'
import '../../style/globals.css'
import Header from '@/components/UI/header'
import AuthLayout from '@/components/layout/auth-layout'
import MainLayout from '@/components/layout/main-layout'



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export function generateStaticParams() {
  return i18nConfig.locales.map(locale => ({ locale }));
}
export default  function  RootLayout({
  children,
  params: { locale }
}) {
  const token = null

  return (
    
    <html lang={locale} dir={dir(locale)}>
      <body >
        {
          token ? <AuthLayout>
            {children}
          </AuthLayout> :
            <MainLayout>
          {children}
          </MainLayout>
        }
    
      </body>
    </html>
  )
}
